#!/bin/bash
SCRIPTDIR="$(dirname $0)"
source "$SCRIPTDIR/docker/scripts/sudo.sh"

DOCKER_REPOSITORY="gitlab.version.fz-juelich.de:5555/rittich2/allium"
VERSION="$(date +%Y-%m-%dT%H-%M)"

docker/scripts/build.sh
$SUDO docker image tag allium-minimal "${DOCKER_REPOSITORY}/allium-minimal:$VERSION" &&
$SUDO docker image tag allium-full "${DOCKER_REPOSITORY}/allium-full:$VERSION" &&
$SUDO docker push "${DOCKER_REPOSITORY}/allium-minimal:$VERSION" &&
$SUDO docker push "${DOCKER_REPOSITORY}/allium-full:$VERSION" &&

tee .gitlab-ci.yml << EOF
# This file was automatically generated by $(basename "$0").
# Do not edit manually.
stages:
  - tests

default:
  image: "${DOCKER_REPOSITORY}/allium-full:$VERSION"
  tags:
    - public-docker
  before_script:
    - pwd
    - ln -s \$PWD /home/developer/source

test_suite_minimal:
  stage: tests
  image: "${DOCKER_REPOSITORY}/allium-minimal:$VERSION"
  script:
    - container-init.sh tests

test_suite_full:
  stage: tests
  script:
    - container-init.sh tests
EOF

