var annotated_dup =
[
    [ "allium", null, [
      [ "Comm", "classallium_1_1Comm.html", "classallium_1_1Comm" ],
      [ "IpcInit", "classallium_1_1IpcInit.html", "classallium_1_1IpcInit" ],
      [ "CgSolverBase", "classallium_1_1CgSolverBase.html", "classallium_1_1CgSolverBase" ],
      [ "CgSolver", "classallium_1_1CgSolver.html", "classallium_1_1CgSolver" ],
      [ "EigenSparseMatrixStorage", "classallium_1_1EigenSparseMatrixStorage.html", "classallium_1_1EigenSparseMatrixStorage" ],
      [ "EigenVectorStorage", "classallium_1_1EigenVectorStorage.html", "classallium_1_1EigenVectorStorage" ],
      [ "GmresSolverBase", "classallium_1_1GmresSolverBase.html", "classallium_1_1GmresSolverBase" ],
      [ "IterativeSolverBase", "classallium_1_1IterativeSolverBase.html", "classallium_1_1IterativeSolverBase" ],
      [ "IterativeSolverMixin", "classallium_1_1IterativeSolverMixin.html", "classallium_1_1IterativeSolverMixin" ],
      [ "LinearOperator", "classallium_1_1LinearOperator.html", "classallium_1_1LinearOperator" ],
      [ "FunctorLinearOperator", "classallium_1_1FunctorLinearOperator.html", "classallium_1_1FunctorLinearOperator" ],
      [ "LinearSolver", "classallium_1_1LinearSolver.html", "classallium_1_1LinearSolver" ],
      [ "MatrixEntry", "classallium_1_1MatrixEntry.html", "classallium_1_1MatrixEntry" ],
      [ "LocalCooMatrix", "classallium_1_1LocalCooMatrix.html", "classallium_1_1LocalCooMatrix" ],
      [ "LocalMatrix", "classallium_1_1LocalMatrix.html", "classallium_1_1LocalMatrix" ],
      [ "LocalVector", "classallium_1_1LocalVector.html", "classallium_1_1LocalVector" ],
      [ "PetscAbstractVectorStorage", "classallium_1_1PetscAbstractVectorStorage.html", "classallium_1_1PetscAbstractVectorStorage" ],
      [ "PetscAbstractVectorStorage< PetscScalar >", "classallium_1_1PetscAbstractVectorStorage_3_01PetscScalar_01_4.html", "classallium_1_1PetscAbstractVectorStorage_3_01PetscScalar_01_4" ],
      [ "PetscObjectPtr", "classallium_1_1PetscObjectPtr.html", "classallium_1_1PetscObjectPtr" ],
      [ "PetscSparseMatrixStorage", "classallium_1_1PetscSparseMatrixStorage.html", "classallium_1_1PetscSparseMatrixStorage" ],
      [ "PetscSparseMatrixStorage< PetscScalar >", "classallium_1_1PetscSparseMatrixStorage_3_01PetscScalar_01_4.html", "classallium_1_1PetscSparseMatrixStorage_3_01PetscScalar_01_4" ],
      [ "PetscVectorStorage", "classallium_1_1PetscVectorStorage.html", "classallium_1_1PetscVectorStorage" ],
      [ "SparseMatrixStorage", "classallium_1_1SparseMatrixStorage.html", "classallium_1_1SparseMatrixStorage" ],
      [ "VectorSpec", "classallium_1_1VectorSpec.html", "classallium_1_1VectorSpec" ],
      [ "LocalSlice", "classallium_1_1LocalSlice.html", "classallium_1_1LocalSlice" ],
      [ "VectorStorage", "classallium_1_1VectorStorage.html", "classallium_1_1VectorStorage" ],
      [ "VectorStorageTrait", "classallium_1_1VectorStorageTrait.html", "classallium_1_1VectorStorageTrait" ],
      [ "VectorTrait", "classallium_1_1VectorTrait.html", "classallium_1_1VectorTrait" ],
      [ "Init", "classallium_1_1Init.html", "classallium_1_1Init" ],
      [ "LocalMesh", "classallium_1_1LocalMesh.html", "classallium_1_1LocalMesh" ],
      [ "IPetscMesh", "classallium_1_1IPetscMesh.html", "classallium_1_1IPetscMesh" ],
      [ "PetscMesh", "classallium_1_1PetscMesh.html", "classallium_1_1PetscMesh" ],
      [ "PetscLocalMesh", "classallium_1_1PetscLocalMesh.html", "classallium_1_1PetscLocalMesh" ],
      [ "PetscMeshValues", "classallium_1_1PetscMeshValues.html", "classallium_1_1PetscMeshValues" ],
      [ "PetscMeshValues< PetscScalar, 2, is_mutable >", "classallium_1_1PetscMeshValues_3_01PetscScalar_00_012_00_01is__mutable_01_4.html", "classallium_1_1PetscMeshValues_3_01PetscScalar_00_012_00_01is__mutable_01_4" ],
      [ "PetscMeshSpec", "classallium_1_1PetscMeshSpec.html", null ],
      [ "PetscMeshSpec< 2 >", "classallium_1_1PetscMeshSpec_3_012_01_4.html", "classallium_1_1PetscMeshSpec_3_012_01_4" ],
      [ "Point", "classallium_1_1Point.html", "classallium_1_1Point" ],
      [ "RangeIterator", "classallium_1_1RangeIterator.html", "classallium_1_1RangeIterator" ],
      [ "Range", "classallium_1_1Range.html", "classallium_1_1Range" ],
      [ "RegularMesh", "classallium_1_1RegularMesh.html", null ],
      [ "ExplicitEuler", "classallium_1_1ExplicitEuler.html", "classallium_1_1ExplicitEuler" ],
      [ "ExplicitIntegrator", "classallium_1_1ExplicitIntegrator.html", "classallium_1_1ExplicitIntegrator" ],
      [ "ImexEulerBase", "classallium_1_1ImexEulerBase.html", "classallium_1_1ImexEulerBase" ],
      [ "ImexEuler", "classallium_1_1ImexEuler.html", "classallium_1_1ImexEuler" ],
      [ "ImexIntegrator", "classallium_1_1ImexIntegrator.html", "classallium_1_1ImexIntegrator" ],
      [ "Integrator", "classallium_1_1Integrator.html", "classallium_1_1Integrator" ],
      [ "RungeKutta4", "classallium_1_1RungeKutta4.html", "classallium_1_1RungeKutta4" ],
      [ "assertion_failed", "classallium_1_1assertion__failed.html", "classallium_1_1assertion__failed" ],
      [ "Cloneable", "classallium_1_1Cloneable.html", "classallium_1_1Cloneable" ],
      [ "CrtpTrait", "structallium_1_1CrtpTrait.html", "structallium_1_1CrtpTrait" ],
      [ "not_implemented", "classallium_1_1not__implemented.html", "classallium_1_1not__implemented" ],
      [ "narrow_number", "structallium_1_1narrow__number.html", null ],
      [ "Polynomial", "classallium_1_1Polynomial.html", "classallium_1_1Polynomial" ]
    ] ],
    [ "AppleTree", "classAppleTree.html", "classAppleTree" ]
];