var dir_e4d27197765b21b9cd993455c22bdca7 =
[
    [ "cg.hpp", "cg_8hpp_source.html", null ],
    [ "cg.impl.hpp", "cg_8impl_8hpp_source.html", null ],
    [ "cuda_array.hpp", "cuda__array_8hpp_source.html", null ],
    [ "cuda_util.hpp", "cuda__util_8hpp_source.html", null ],
    [ "cuda_vector.hpp", "cuda__vector_8hpp_source.html", null ],
    [ "default.hpp", "default_8hpp_source.html", null ],
    [ "eigen_sparse_matrix.hpp", "eigen__sparse__matrix_8hpp_source.html", null ],
    [ "eigen_vector.hpp", "eigen__vector_8hpp_source.html", null ],
    [ "eigen_vector.impl.hpp", "eigen__vector_8impl_8hpp_source.html", null ],
    [ "gmres.hpp", "gmres_8hpp_source.html", null ],
    [ "gmres.impl.hpp", "gmres_8impl_8hpp_source.html", null ],
    [ "iterative_solver.hpp", "iterative__solver_8hpp_source.html", null ],
    [ "linear_operator.hpp", "linear__operator_8hpp_source.html", null ],
    [ "linear_solver.hpp", "linear__solver_8hpp_source.html", null ],
    [ "local_coo_matrix.hpp", "local__coo__matrix_8hpp_source.html", null ],
    [ "local_matrix.hpp", "local__matrix_8hpp_source.html", null ],
    [ "local_vector.hpp", "local__vector_8hpp_source.html", null ],
    [ "petsc_abstract_vector.hpp", "petsc__abstract__vector_8hpp_source.html", null ],
    [ "petsc_object_ptr.hpp", "petsc__object__ptr_8hpp_source.html", null ],
    [ "petsc_sparse_matrix.hpp", "petsc__sparse__matrix_8hpp_source.html", null ],
    [ "petsc_util.hpp", "petsc__util_8hpp_source.html", null ],
    [ "petsc_vector.hpp", "petsc__vector_8hpp_source.html", null ],
    [ "sparse_matrix.hpp", "sparse__matrix_8hpp_source.html", null ],
    [ "txt_io.hpp", "txt__io_8hpp_source.html", null ],
    [ "vector_spec.hpp", "vector__spec_8hpp_source.html", null ],
    [ "vector_storage.hpp", "vector__storage_8hpp_source.html", null ],
    [ "vector_storage.impl.hpp", "vector__storage_8impl_8hpp_source.html", null ],
    [ "vector_trait.hpp", "vector__trait_8hpp_source.html", null ]
];